action: train
name: gtd12againtry_trn
modality: ["RGB"] # modality used
total_batch: 128 # total batch size if training is done with gradient accumulation
batch_size: 32 # batch size for the forward
gpus: null # gpus adopted
wandb_name: null 
resume_from: 
logname: null 
models_dir: /content/drive/MyDrive/MLDL23/mldl23-ego/mldl23-ego/models # directory containing all the models

train:
  num_iter: 5000 # was 5000 number of training iterations with total_batch size
  lr_steps: 3000 #was 3000 steps before reducing learning rate
  eval_freq: 50 # evaluation frequency
  num_clips: 5 # clips adopted in training # was 1
  dense_sampling: # sampling version adopted in training for each modality
    RGB: True
  num_frames_per_clip: # number of frames adopted in training for each modality
    RGB: 16

test:
  num_clips: 5 # number of clips in testing
  dense_sampling: # sampling version adopted in test for each modality
    RGB: True
  num_frames_per_clip: # number of frames adopted in test for each modality
    RGB: 16

dataset:
  annotations_path: train_val # path for the annotations data
  shift: D1-D2 # shifts of the dataset
  workers: 4 # number of workers for the dataloader
  stride: 2 # stride in case of dense sampling
  resolution: 224 # input resolution to the model
  RGB:
    data_path: /content/ek_data/frames # path to RGB data
    tmpl: "img_{:010d}.jpg" # format of RGB filenames
    features_name: change_me
  Event: # not neeeded for the project
    rgb4e: 6

# these are the action recognition models for each modality
models:
  RGB:
    model: Classifier
    weight:
      GSD: 0
      GVD: 1
      GRD: 0
      Attn: 0
    reduce_factor: 0.1
    frame_aggregation: 'trn'
    normalize: False
    kwargs: {}
    lr_steps: 1500 #was 3000
    lr: 0.01 #was 0.01
    sgd_momentum: 0.9
    weight_decay: 1e-7
    